name: Build Release

on:
  workflow_dispatch:
  release:

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: master

      - name: Download WASM4
        uses: robinraju/release-downloader@v1.3
        with:
          repository: aduros/wasm4
          tag: v2.2.0
          fileName: w4-linux.zip

      - name: Unzip WASM4
        run: |
          unzip w4-linux.zip
          rm -f w4-linux.zip

      - name: Build the release
        run: |
          zig build -Drelease-small
          ./w4 bundle build/cart.wasm --title "Crossing Party Lines" index.html
