name: Smoke Tests

on: pull_request

env:
  INSTALL_EDM_VERSION: 3.3.1

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup EDM (Python)
        uses: enthought/setup-edm-action@v1
        with:
          edm-version: ${{ env.INSTALL_EDM_VERSION }}

      - name: Install EDM Environment
        run: edm --config ci/edm.yaml install -y click pillow

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: master

      - name: Run checks
        run: |
          zig build
          edm run -- python -m ci img-norm --check
